name: Deploy to eniac
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_WEBSITE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Push to eniac
        uses: appleboy/[email protected]
        with:
          host: eniac.seas.upenn.edu
          username: bhavanam
          key: ${{ secrets.DEPLOY_KEY_WEBSITE }}
          script: |
            cd ~/public_html
            ./update_website.sh
