---
name: Deploy to eniac
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_WEBSITE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Run remote deploy script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: eniac.seas.upenn.edu
          username: bhavanam
          key: ${{ secrets.DEPLOY_KEY_WEBSITE }}
          script: |
            cd ~/public_html
            ./update_website.sh
