name: Compile CV

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create assets directory
        run: mkdir -p assets
      
      # Alternative approach - compile from your existing LaTeX files
      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          working_directory: ./
          args: -pdf -file-line-error -halt-on-error
          
      - name: Move compiled PDF
        run: |
          mkdir -p assets
          cp resume.pdf assets/Bhavana_Mehta_Resume.pdf || echo "No PDF found"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets || echo "No assets to add"
          git commit -m "Update CV" || echo "No changes to commit"
          git push